language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
notifications:
  email:
    recipients:
    - neraliu@yahoo-inc.com
    - adon@yahoo-inc.com
  on_success: change
  on_failure: always
after_success:
- test $(cat $TRAVIS_BUILD_DIR/package.json | grep version | awk '{print $2}' | sed 's/"//g' | sed 's/,//g' | awk '{print "v"$1}' ) = $TRAVIS_TAG && test $(echo $TRAVIS_NODE_VERSION | awk '{print $1}' ) = '0.12' && export VALID_VERSION=true
deploy:
  provider: npm
  email: neraliu@yahoo-inc.com
  api_key:
    secure: IAl277fa7yO+lDlPveRw2gDikCnwtiLvZsGDEtXzmhaPmHT98zrtUqd8dy+9CmQi9GaGz5o+1kE5DuhSQKi6XT2W2g5WgEEy++vlcg01X8+bH5zNfpyGmvbTtZj2JYX4GJExAuY02APuKEAAfc9S+S5QITWpqOW7IcjkDYhzkMI=
  on:
    condition: $VALID_VERSION = true
    tags: true
    branch: master
